In [1]:
#numpy -> numerical python, creates n-d array
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([1,2,3,4,5, 'hello', 'python'])

array(['1', '2', '3', '4', '5', 'hello', 'python'], dtype='<U21')

In [4]:
np.array([ [1,2,3], [4,5,6], [7,8,9] ])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.random.random()

0.25701164758095496

In [6]:
np.random.random(10)

array([0.81043248, 0.29802809, 0.3228358 , 0.44019071, 0.99521253,
       0.06823738, 0.2376055 , 0.17139249, 0.89733877, 0.25674356])

In [16]:
arr = np.random.random([3,3,3,3])

In [17]:
arr.shape

(3, 3, 3, 3)

In [18]:
arr.ndim

4

In [19]:
arr.min()

0.007927897209472734

In [20]:
arr.max()

0.9951700456430573

In [21]:
arr.mean()

0.489270501140586

In [22]:
arr.argmin()

42